InvestmentChecker/Models/ErrorViewModel.cs
using System;

namespace InvestmentChecker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InvestmentChecker/Models/Finnhub/CryptoQuote.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InvestmentChecker.Models.Finnhub
{
    public class CryptoQuote
    {
        public CryptoQuote(IEnumerable<double> closePrice, IEnumerable<double> highPrice, IEnumerable<double> lowPrice, IEnumerable<double> openPrice, string status, IEnumerable<int> timestamp, IEnumerable<double> volume)
        {
            ClosePrice = closePrice;
            HighPrice = highPrice;
            LowPrice = lowPrice;
            OpenPrice = openPrice;
            Status = status;
            TimeStamp = timestamp;
            Volume = volume;
        }

        [JsonProperty("c")]
        public IEnumerable<double> ClosePrice { get; set; }

        [JsonProperty("h")]
        public IEnumerable<double> HighPrice { get; set; }

        [JsonProperty("l")]
        public IEnumerable<double> LowPrice { get; set; }

        [JsonProperty("o")]
        public IEnumerable<double> OpenPrice { get; set; }

        [JsonProperty("s")]
        public string Status { get; set; }

        [JsonProperty("t")]
        public IEnumerable<int> TimeStamp { get; set; }

        [JsonProperty("v")]
        public IEnumerable<double> Volume { get; set; }
    }
}

InvestmentChecker/Models/Finnhub/CryptoSymbol.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InvestmentChecker.Models.Finnhub
{
    public class CryptoSymbol
    {
        public CryptoSymbol()
        {

        }
        public CryptoSymbol(string symbol)
        {
            Symbol = symbol;
        }
        public string Symbol { get; set; }

    }
}

InvestmentChecker/Models/Finnhub/StockQuote.cs
using Newtonsoft.Json;

namespace InvestmentChecker.Models.Finnhub
{
    public class StockQuote
    {
        public StockQuote(double currentPrice, double change, double percentChange, double highPrice, double lowPrice, double openPrice, double previousClose)
        {
            CurrentPrice = currentPrice;
            Change = change;
            PercentChange = percentChange;
            HighPrice = highPrice;
            LowPrice = lowPrice;
            OpenPrice = openPrice;
            PreviousClose = previousClose;
        }

        [JsonProperty("c")]
        public double CurrentPrice { get; set; }

        [JsonProperty("d")]
        public double Change { get; set; }

        [JsonProperty("dp")]
        public double PercentChange { get; set; }

        [JsonProperty("h")]
        public double HighPrice { get; set; }

        [JsonProperty("l")]
        public double LowPrice { get; set; }

        [JsonProperty("o")]
        public double OpenPrice { get; set; }

        [JsonProperty("pc")]
        public double PreviousClose { get; set; }
    }
}

InvestmentChecker/Models/Finnhub/StockSymbol.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InvestmentChecker.Models.Finnhub
{
    public class StockSymbol
    {
        public StockSymbol()
        {

        }
        public StockSymbol(string symbol)
        {
            Symbol = symbol;
        }
        public string Symbol { get; set; }
    }
}

InvestmentChecker/Controllers/FinnhubController.cs
using InvestmentChecker.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InvestmentChecker.Controllers
{
    public class FinnhubController : Controller
    {
        private readonly IFinnhubService _finnhubService;

        public FinnhubController(IFinnhubService finnhubService)
        {
            _finnhubService = finnhubService;
        }

        [HttpGet]
        public ActionResult GetCurrentStockPriceBySymbol(string symbol)
        {
            var quote = _finnhubService.GetCurrentStockPrice(symbol);

            ViewBag.Symbol = symbol;
            ViewBag.Quote = quote.Result;

            return View("DisplayStockResults");
        }

        [HttpGet]
        public ActionResult GetCryptoPrice(string symbol)
        {
            var quote = _finnhubService.GetCryptoPrice(symbol);

            ViewBag.Symbol = symbol;
            ViewBag.Price = quote.Result.ClosePrice.First();

            return View("DisplayCryptoResults");
        }

        public ActionResult SelectStock()
        {
            return View();
        }

        public ActionResult SelectCrypto()
        {
            return View();
        }
    }
}

InvestmentChecker/Controllers/HomeController.cs
using InvestmentChecker.Models;
using InvestmentChecker.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InvestmentChecker.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InvestmentChecker/Views/Finnhub/DisplayCryptoResults.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!DOCTYPE html>
    <html lang="en">
    <body>
        <div class="text-center">
            <h1>Crypto Symbol: @ViewBag.Symbol</h1>
            <h2>Current Price: @ViewBag.Price</h2>

        </div>

        <div>
            @Html.ActionLink("Back", "Index", "Home")
        </div>
    </body>
</html>
}

InvestmentChecker/Views/Finnhub/DisplayStockResults.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!DOCTYPE html>
    <html lang="en">
    <body>
        <div class="text-center">
            <h1>Stock Symbol: @ViewBag.Symbol</h1>
            <h2>Current Price: @ViewBag.Quote.CurrentPrice</h2>
          
        </div>

        <div>
            @Html.ActionLink("Back", "Index", "Home")
        </div>
    </body>
</html>
}

InvestmentChecker/Views/Finnhub/SelectCrypto.cshtml
@model InvestmentChecker.Models.Finnhub.CryptoSymbol
@{
    <!DOCTYPE html>
    <html lang="en">
    <body>
        <div class="text-center">
            @using (Html.BeginForm("GetCryptoPrice", "Finnhub", FormMethod.Get))
            {
                @Html.TextBoxFor(c => c.Symbol, new { @class = "form-control", placeholder = "Crypto Symbol...", name = "symbol" })
                <br />
                <input type="submit" class="btn-primary" value="Submit" />
            }

            <div>
                @Html.ActionLink("Back", "Index", "Home")
            </div>
        </div>
    </body>
</html>

}

InvestmentChecker/Views/Finnhub/SelectStock.cshtml
@model InvestmentChecker.Models.Finnhub.StockSymbol
@{
    <!DOCTYPE html>
    <html lang="en">
    <body>
        <div class="text-center">
            @using (Html.BeginForm("GetCurrentStockPriceBySymbol", "Finnhub", FormMethod.Get))
            {
                @Html.TextBoxFor(s => s.Symbol, new { @class = "form-control", placeholder = "Stock Symbol...", name = "symbol" })
                <br />
                <input type="submit" class="btn-primary" value="Submit" />
            }

            <div>
                @Html.ActionLink("Back", "Index", "Home")
            </div>
        </div>
    </body>
</html>

}

InvestmentChecker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <button type="button" class="btn btn-outline-secondary"><a asp-controller="Finnhub" asp-action="SelectStock">Stock</a></button>
    <button type="button" class="btn btn-outline-secondary"><a asp-controller="Finnhub" asp-action="SelectCrypto">Crypto</a></button>
</div>

InvestmentChecker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvestmentChecker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InvestmentChecker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InvestmentChecker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>